package gnome

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/vula-os/vula/internal/config"
)

type ExtensionMeta struct {
	UUID        string
	Name        string
	Description string
	Essential   bool
}

type Manager struct {
	cfg *config.Config
}

func NewManager(cfg *config.Config) *Manager {
	return &Manager{cfg: cfg}
}

var RecommendedExtensions = []ExtensionMeta{
	{
		UUID:        "tiling-assistant@leleat-on-github",
		Name:        "Tiling Assistant",
		Description: "Advanced window snapping, auto-tiling, layouts, and gaps",
		Essential:   true,
	},
	{
		UUID:        "blur-my-shell@aunetx",
		Name:        "Blur my Shell",
		Description: "Modern glassmorphism blur effects for panel and overview",
		Essential:   true,
	},
	{
		UUID:        "appindicatorsupport@rgcjonas.gmail.com",
		Name:        "AppIndicator Support",
		Description: "System tray icons for background services",
		Essential:   true,
	},
	{
		UUID:        "just-perfection-desktop@just-perfection",
		Name:        "Just Perfection",
		Description: "Fine-grained control to minimize GNOME Shell UI clutter",
		Essential:   false,
	},
}

// SetDconfKey applies a dconf setting via dconf write or gsettings
func SetDconfKey(schema, key, value string) error {
	cmd := exec.Command("gsettings", "set", schema, key, value)
	return cmd.Run()
}

// GetDconfKey retrieves a dconf setting
func GetDconfKey(schema, key string) (string, error) {
	out, err := exec.Command("gsettings", "get", schema, key).Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// GetDconfKeyPath retrieves a dconf key at an explicit dconf path
func GetDconfKeyPath(path, key string) (string, error) {
	fullPath := path + key
	out, err := exec.Command("dconf", "read", fullPath).Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// RegisterCustomKeybinding registers or updates a custom keybinding by ID in dconf
func RegisterCustomKeybinding(id, name, command, binding string) error {
	path := fmt.Sprintf("/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom-vula-%s/", id)
	_ = exec.Command("dconf", "write", path+"name", fmt.Sprintf("'%s'", name)).Run()
	_ = exec.Command("dconf", "write", path+"command", fmt.Sprintf("'%s'", command)).Run()
	_ = exec.Command("dconf", "write", path+"binding", fmt.Sprintf("'%s'", binding)).Run()

	// Update list of custom keybindings array
	out, _ := exec.Command("dconf", "read", "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings").Output()
	rawList := strings.TrimSpace(string(out))

	if !strings.Contains(rawList, path) {
		if rawList == "" || rawList == "@as []" || rawList == "[]" {
			rawList = fmt.Sprintf("['%s']", path)
		} else {
			rawList = strings.TrimSuffix(rawList, "]") + fmt.Sprintf(", '%s']", path)
		}
		_ = exec.Command("dconf", "write", "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings", rawList).Run()
	}

	return nil
}

// ApplyDesktopOptimizations tunes GNOME Shell for high performance and developer ergonomics
func (m *Manager) ApplyDesktopOptimizations() error {
	// 1. Dark Mode
	_ = SetDconfKey("org.gnome.desktop.interface", "color-scheme", "'prefer-dark'")
	_ = SetDconfKey("org.gnome.desktop.interface", "gtk-theme", "'Yaru-dark'")

	// 2. Window management tweaks
	_ = SetDconfKey("org.gnome.desktop.wm.preferences", "button-layout", "'appmenu:close'")
	_ = SetDconfKey("org.gnome.mutter", "center-new-windows", "true")
	_ = SetDconfKey("org.gnome.mutter", "attach-modal-dialogs", "true")

	// 3. Fonts
	_ = SetDconfKey("org.gnome.desktop.interface", "font-name", "'Ubuntu Sans 11'")
	_ = SetDconfKey("org.gnome.desktop.interface", "monospace-font-name", "'JetBrains Mono 11'")

	// 4. Panel Glassmorphism & Visual Uncluttering (Blur my Shell & Just Perfection)
	_ = SetDconfKey("org.gnome.shell.extensions.blur-my-shell.panel", "blur", "true")
	_ = SetDconfKey("org.gnome.shell.extensions.blur-my-shell.panel", "sigma", "30")
	_ = SetDconfKey("org.gnome.shell.extensions.blur-my-shell.panel", "brightness", "0.75")
	_ = SetDconfKey("org.gnome.shell.extensions.just-perfection", "accessibility-menu", "false")
	_ = SetDconfKey("org.gnome.shell.extensions.just-perfection", "clock-menu-position", "1")

	// 5. Configure Developer Keybindings
	return m.ConfigureKeybindings()
}

// EnsureHUDLauncherScript creates ~/.local/bin/vula-hud-launch for floating, always-on-top, persistent HUD window
func EnsureHUDLauncherScript() error {
	home := os.Getenv("HOME")
	binDir := filepath.Join(home, ".local", "bin")
	_ = os.MkdirAll(binDir, 0755)

	scriptPath := filepath.Join(binDir, "vula-hud-launch")
	content := `#!/bin/bash
# Auto-generated by Vula Desktop Manager
# Launches Vula HUD in a floating, always-on-top, persistent window

VULA_BIN="$HOME/.local/bin/vula"

(
  sleep 0.3
  if command -v wmctrl &>/dev/null; then
    wmctrl -r "Vula HUD" -b add,above,sticky 2>/dev/null || true
  fi
) &

if command -v ghostty &>/dev/null; then
    ghostty --title="Vula HUD" \
            --class="vula-hud" \
            --window-height=18 \
            --window-width=38 \
            --window-decorations=false \
            --gtk-single-instance=false \
            -e "$VULA_BIN" hud
elif command -v gnome-terminal &>/dev/null; then
    gnome-terminal --class="vula-hud" --title="Vula HUD" --geometry=38x18 -- "$VULA_BIN" hud
else
    xterm -title "Vula HUD" -geometry 38x18 -e "$VULA_BIN" hud
fi
`
	return os.WriteFile(scriptPath, []byte(content), 0755)
}

// ConfigureKeybindings sets up keyboard-centric shortcuts
func (m *Manager) ConfigureKeybindings() error {
	_ = EnsureHUDLauncherScript()

	// 0. Free <Super>space from GNOME's switch-input-source so it triggers Vula HUD
	_ = SetDconfKey("org.gnome.desktop.wm.keybindings", "switch-input-source", "[]")
	_ = SetDconfKey("org.gnome.desktop.wm.keybindings", "switch-input-source-backward", "[]")

	home := os.Getenv("HOME")
	vulaBin := filepath.Join(home, ".local", "bin", "vula")
	hudBin := filepath.Join(home, ".local", "bin", "vula-hud-launch")
	voiceBin := vulaBin + " voice record"
	listenBin := vulaBin + " listen"
	explainBin := vulaBin + " ai explain"
	keysBin := fmt.Sprintf("gnome-terminal --title=\"Vula Keybindings\" -- %s keys", vulaBin)

	// Register Vula Custom Keybindings
	_ = RegisterCustomKeybinding("hud", "Vula HUD", hudBin, "<Super>space")
	_ = RegisterCustomKeybinding("voice_dictate", "Vula Voice Dictate", voiceBin, "<Super><Alt>v")
	_ = RegisterCustomKeybinding("voice_assistant", "Vula Voice AI Assistant", listenBin, "<Super><Alt>a")
	_ = RegisterCustomKeybinding("ai_explain", "Vula AI Explain Selection", explainBin, "<Super><Alt>c")
	_ = RegisterCustomKeybinding("keys_map", "Vula Keybindings Cheat-Sheet", keysBin, "<Super><Shift>k")

	// Core navigation shortcuts
	_ = SetDconfKey("org.gnome.desktop.wm.keybindings", "close", "['<Super>q', '<Alt>F4']")
	_ = SetDconfKey("org.gnome.desktop.wm.keybindings", "toggle-maximized", "['<Super>m']")

	return nil
}

// ListInstalledExtensions returns enabled extension UUIDs
func ListInstalledExtensions() ([]string, error) {
	out, err := exec.Command("gnome-extensions", "list", "--enabled").Output()
	if err != nil {
		return nil, err
	}
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	var result []string
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result, nil
}

// EnableExtension enables a GNOME shell extension by UUID
func EnableExtension(uuid string) error {
	cmd := exec.Command("gnome-extensions", "enable", uuid)
	return cmd.Run()
}
